### ISSUE TITLE
Calling getMetadata crashes the app

### ISSUE THREAD

**Issue by harryio** [wseemann/FFmpegMediaPlayer#124]
I'm trying to fetch ICY metadata from the stream by calling `getMetadata()` on the instance of `FFmpegMediaPlayer` like this:

```Java
mediaPlayer.setOnInfoListener(this);

@Override
public boolean onInfo(FFmpegMediaPlayer mp, int what, int extra) {
    if (what == FFmpegMediaPlayer.MEDIA_INFO_METADATA_UPDATE) {
         mp.getMetadata();
    }

    return false;
}
```

But the app is crashing when I call the `getMetadata()` function. If I remove the function and run the app then there is no crash. The only crash log of the issue I can find is:
```
V/FFmpegMediaPlayer-JNI: native_init
V/FFmpegMediaPlayer-JNI: native_setup
V/FFmpegMediaPlayer-JNI: setAudioStreamType: 3
V/FFmpegMediaPlayer-JNI: setDataSource: path ...
V/FFmpegMediaPlayer-JNI: notify: 200
I/FFmpegMediaPlayer: Info (802,0)
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 18550 (app.packagename)
```
If you need more infomation, just tell me how to get it and I will post it here.

**Comment by abuharsky** [comment]
same problem

**Comment by wseemann** [comment]
Fixed in latest release.

**Comment by thalisvilela** [comment]
This problem is still present... same error log here. Using Genymotion.
